// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZjkgjaf_KUoy-YBcWpX0xTpiPjT76clc',
    appId: '1:215254213048:web:40dd809dc3a4d43f556f4d',
    messagingSenderId: '215254213048',
    projectId: 'secret-lambda-403915',
    authDomain: 'secret-lambda-403915.firebaseapp.com',
    storageBucket: 'secret-lambda-403915.appspot.com',
    measurementId: 'G-DD20FLTV50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV38z98tdlXlt004N9-hCLkbNvNK7Qvak',
    appId: '1:215254213048:android:f0dae0b33ad2d269556f4d',
    messagingSenderId: '215254213048',
    projectId: 'secret-lambda-403915',
    storageBucket: 'secret-lambda-403915.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrO3DMp0FW_ENWhhJCcKy0-0wk-flcIog',
    appId: '1:215254213048:ios:bacc04d09a4c35ef556f4d',
    messagingSenderId: '215254213048',
    projectId: 'secret-lambda-403915',
    storageBucket: 'secret-lambda-403915.appspot.com',
    androidClientId: '215254213048-8rf3pieiru5upt8jpdelmmhusuvk77v2.apps.googleusercontent.com',
    iosClientId: '215254213048-s5je8ush6cjisdbvuja8eapr9iv7irqi.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.6amMartDelivery',
  );
}
